version: '2.4'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    expose:
      - 8090
    ports:
      - "8090:8090"
    environment:
      GIN_MODE: "release"
      APP_DEBUG: "true"
      APP_BIND_ADDR: "0.0.0.0:8090"
      API_DEBUG: "true"
      API_BIND_ADDR: "0.0.0.0:80"
      BITMEX_WS_URL: "wss://testnet.bitmex.com/realtime"
      DB_HOST: "mysql"
      DB_SLAVE_HOST_1: "mysql"
      DB_SLAVE_HOST_2: "mysql"
      DB_NAME: "app"
      DB_USER: "admin"
      DB_PASSWORD: "kd98qw11"
    restart: on-failure
    depends_on:
      - mysql

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    expose:
      - 80
    ports:
      - "80:80"
    environment:
      GIN_MODE: "release"
      APP_DEBUG: "true"
      APP_BIND_ADDR: "0.0.0.0:8090"
      API_DEBUG: "true"
      API_BIND_ADDR: "0.0.0.0:80"
      BITMEX_WS_URL: "wss://testnet.bitmex.com/realtime"
      DB_HOST: "mysql"
      DB_SLAVE_HOST_1: "mysql"
      DB_SLAVE_HOST_2: "mysql"
      DB_NAME: "app"
      DB_USER: "admin"
      DB_PASSWORD: "kd98qw11"
    restart: on-failure
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - mysql_storage:/var/lib/mysql
      - ./docker/config/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "kd98qw11"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

volumes:
  mysql_storage: